[package]
name = "distributed_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "2.1.4", features = ["postgres","r2d2"] }
lazy_static = "1.4.0"
odbc-api = "6.0.2"
