CREATE TABLE databases (
	id	SERIAL	PRIMARY KEY,
	name	VARCHAR(32) NOT NULL,
	uri	VARCHAR(32) NOT NULL,
	username	VARCHAR(32) NOT NULL,
    pass	VARCHAR(32) NOT NULL
);

CREATE TABLE schemas (
	database_id	INTEGER NOT NULL,
	id	SERIAL	PRIMARY KEY,
	name	VARCHAR(32) NOT NULL
);

CREATE TABLE tables (
	schema_id	INTEGER NOT NULL,
	id	SERIAL	PRIMARY KEY,
	name	VARCHAR(32) NOT NULL
);

CREATE TABLE columns (
	table_id	INTEGER NOT NULL,
	id	SERIAL	PRIMARY KEY,
	name	VARCHAR(32) NOT NULL
);

CREATE DATABASE test;
\c test
CREATE TABLE test_table (
	hello	VARCHAR(32),
	goodbye	VARCHAR(32)
);